---
- name: OS-specific variables included
  include_vars: "{{ ansible_os_family }}.yml"

- name: Bind enabled and service started
  service:
    name: "{{ authns_service }}"
    enabled: yes
    state: started
