---
- name: OS-specific variables included
  include_vars: "{{ ansible_os_family }}.yml"

- name: Bind nameserver installed
  loop: "{{ authns_server_packages }}"
  package:
    name: "{{ item }}"
    state: present
