---
- name: Bind nameserver installed
  loop: "{{ authns_packages }}"
  package:
    name: "{{ item }}"
    state: present

- name: Bind configured as authoritative-only nameserver
  template:
    src: named.conf.options.j2
    dest: "{{ authns_bind_options_file }}"
