---
- name: Zone configuration file present
  notify:
    - Bind reloaded
  template:
    src: zone.j2
    dest: "{{ authns_zone_config_file }}"
    owner: root
    group: root
    mode: 0644

- name: Zone database file present
  notify:
    - Bind reloaded
  template:
    src: db.j2
    dest: "{{ authns_zone_db_file }}"
    owner: root
    group: root
    mode: 0644

- name: Zone resource records file present
  notify:
    - Bind reloaded
  copy:
    content: ""
    force: no
    dest: "{{ authns_zone_rr_file }}"
    owner: root
    group: root
    mode: 0644

- name: Zone configuration file included
  notify:
    - Bind reloaded
  lineinfile:
    path: "{{ authns_local_config_file }}"
    line: 'include "{{ authns_zone_config_file }}";'
