---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ns1.centos-authns.example.com
    image: znerolmolecule/molecule-prebuilt:centos-systemd
    tty: yes
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ns2.debian-authns.example.net
    image: znerolmolecule/molecule-prebuilt:debian-systemd
    tty: yes
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ns3.fedora-authns.example.com
    image: znerolmolecule/molecule-prebuilt:fedora-systemd
    tty: yes
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ns4.ubuntu-authns.example.net
    image: znerolmolecule/molecule-prebuilt:ubuntu-systemd
    tty: yes
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      ns1.centos-authns.example.com:
        molecule_authns_key_source: file
        molecule_authns_zone_source: file
      ns2.debian-authns.example.net:
        molecule_authns_key_source: file
        molecule_authns_zone_source: var
      ns3.fedora-authns.example.com:
        ansible_python_interpreter: /usr/bin/python3
        molecule_authns_key_source: var
        molecule_authns_zone_source: file
      ns4.ubuntu-authns.example.net:
        molecule_authns_key_source: var
        molecule_authns_zone_source: var

verifier:
  name: testinfra
  lint:
    name: flake8
