---
- name: Converge
  hosts: all
  vars:
    authns_zone_rr_content: |
      _test 1D IN TXT "test rr"
  tasks:
    - import_role:
        name: ansible-role-authns

    - import_role:
        name: ansible-role-authns
        tasks_from: zone

    - import_role:
        name: ansible-role-authns
        tasks_from: utilities
