---
- name: Converge
  hosts: all
  tasks:
    - import_role:
        name: ansible-role-authns

    - import_role:
        name: ansible-role-authns
        tasks_from: zone

    - import_role:
        name: ansible-role-authns
        tasks_from: utilities
